/*
============================================
; Title:  kimberlin-assignment-2.3
; Author: Professor Krasso
; Date:   January 9 2021
; Modified By: Rhiannon Kimberlin
; Description: Enhanced-Profile-App
;===========================================
*/

//Generated by Angular CLI
import { Component } from '@angular/core';

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.css']
})
//Defining Assignment and isLoggedIn
export class AppComponent {
  //Created isLoggedIn Variable which determines if profile is viewable
  isLoggedIn: Boolean = true;
  //Created Assignment Variable 
  assignment: string = "Assignment 2.3 - Data Binding";
}
