/*
============================================
; Title:  kimberlin-assignment-2.4
; Author: Professor Krasso
; Date:   January 10 2021
; Modified By: Rhiannon Kimberlin
; Description: Composer-app
;===========================================
*/

//Generated by Angular CLI
import { Component } from '@angular/core';

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.css']
})
export class AppComponent {
  assignment: string = "Assignment 2.4 - Routing in Action!";
}
