/*
============================================
; Title:  kimberlin-assignment-3.2
; Author: Professor Krasso
; Date:   January 19 2021
; Modified By: Rhiannon Kimberlin
; Description: Enhanced-Composer-app
;===========================================
*/

//Generated by Angular CLI
import { Component } from '@angular/core';

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.css']
})
export class AppComponent {
  assignment: string = "Assignment 3.2 - Passing Data to Routes, Part 1";
}
