/*
============================================
; Title:  kimberlin-assignment-4.3
; Author: Professor Krasso
; Date:   January 25 2021
; Modified By: Rhiannon Kimberlin
; Description: Reactive-Composer-app
;===========================================
*/

//Generated by Angular CLI
import { Component } from '@angular/core';

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.css']
})
//Assignment Information
export class AppComponent {
  assignment: string = "Assignment 4.3 - Handling Events with Observables";
}
